// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint "github.com/haunguyenctnp/ebanking-gokit/accounts/pkg/endpoint"
	http1 "github.com/haunguyenctnp/ebanking-gokit/accounts/pkg/http"
	service "github.com/haunguyenctnp/ebanking-gokit/accounts/pkg/service"

	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"Create":          {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Create", logger))},
		"Deposit":         {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Deposit", logger))},
		"DepositAccount":  {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "DepositAccount", logger))},
		"Drop":            {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Drop", logger))},
		"GetAccount":      {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetAccount", logger))},
		"Withdraw":        {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Withdraw", logger))},
		"WithdrawAccount": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "WithdrawAccount", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["Deposit"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Deposit")), endpoint.InstrumentingMiddleware(duration.With("method", "Deposit"))}
	mw["Withdraw"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Withdraw")), endpoint.InstrumentingMiddleware(duration.With("method", "Withdraw"))}
	mw["Drop"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Drop")), endpoint.InstrumentingMiddleware(duration.With("method", "Drop"))}
	mw["Create"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Create")), endpoint.InstrumentingMiddleware(duration.With("method", "Create"))}
	mw["GetAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "GetAccount"))}
	mw["DepositAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "DepositAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "DepositAccount"))}
	mw["WithdrawAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "WithdrawAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "WithdrawAccount"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"Deposit", "Withdraw", "Drop", "Create", "GetAccount", "DepositAccount", "WithdrawAccount"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
